# Generated by Django 3.1.2 on 2020-10-04 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twenty_five", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="message",
            new_name="copyright_holder",
        ),
        migrations.AddField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
