# Generated by Django 3.1.2 on 2020-10-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twenty_five', '0002_auto_20201004_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
