# Generated by Django 3.1.2 on 2020-10-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twenty_five', '0003_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
